site_name: Mesh Auto | Gestão de Fluxo
site_description: Documentação técnica do sistema de gestão de oficina profissional.
site_author: Teu Nome

theme:
  name: material
  language: pt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest

nav:
  - Introdução: index.md
  - Arquitetura de Dados: logica-negocio.md
  - Segurança e Sessões: seguranca.md
  - Componentes Técnicos: tecnico.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg