# Generated by Django 6.0.2 on 2026-02-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={},
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('numero_os', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(choices=[('REPARACAO', 'Reparação'), ('MANUTENCAO', 'Manutenção'), ('GARANTIA', 'Garantia')], max_length=20)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('DIAGNOSTICO', 'Em diagnóstico'), ('REPARACAO', 'Em reparação'), ('AGUARDANDO', 'A aguardar peças'), ('FINALIZADO', 'Finalizado'), ('ENTREGUE', 'Entregue')], default='RECEBIDO', max_length=20)),
                ('descricao_avaria', models.TextField(verbose_name='Descrição da avaria ou solicitação')),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True)),
                ('pecas_aplicadas', models.TextField(blank=True, null=True)),
                ('horas_mao_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='gestao.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_proxima_revisao', models.IntegerField(verbose_name='Próxima revisão (km)')),
                ('data_proxima_revisao', models.DateField(verbose_name='Próxima revisão (data)')),
                ('alertas_ativos', models.BooleanField(default=True)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestao.veiculo')),
            ],
        ),
    ]
