# Generated by Django 6.0.2 on 2026-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_veiculo_options_alter_veiculo_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='km_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('REPARACAO', 'Reparação Corretiva'), ('MANUTENCAO', 'Manutenção Preventiva'), ('GARANTIA', 'Garantia')], max_length=20),
        ),
    ]
