# Generated by Django 6.0.2 on 2026-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_veiculo_km_atual_alter_ordemservico_tipo_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planomanutencao',
            name='alertas_ativos',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servicos_executados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
