# Generated by Django 6.0.2 on 2026-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_planomanutencao_alertas_ativos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_avaria',
            field=models.TextField(verbose_name='Avaria/Solicitação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('REPARACAO', 'Reparação'), ('MANUTENCAO', 'Manutenção'), ('GARANTIA', 'Garantia')], max_length=20),
        ),
    ]
