# Generated by Django 6.0.2 on 2026-02-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_ordemservico_descricao_avaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_entrega',
        ),
    ]
