# Generated by Django 6.0.2 on 2026-02-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_remove_ordemservico_data_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='descricao_avaria',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='diagnostico_tecnico',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='horas_mao_obra',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='numero_os',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='pecas_aplicadas',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos_executados',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_servico',
        ),
        migrations.RemoveField(
            model_name='planomanutencao',
            name='data_proxima_revisao',
        ),
        migrations.RemoveField(
            model_name='planomanutencao',
            name='km_proxima_revisao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(default='Geral', verbose_name='Descrição do Serviço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mão de Obra'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_pecas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor das Peças'),
        ),
        migrations.AddField(
            model_name='planomanutencao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planomanutencao',
            name='proxima_revisao_km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.veiculo'),
        ),
    ]
