# Generated by Django 6.0.2 on 2026-02-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_remove_ordemservico_descricao_avaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_mao_de_obra',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='km_atual',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_avaria',
            field=models.TextField(default='A aguardar descrição', verbose_name='Descrição da Avaria/Solicitação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='diagnostico_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico Técnico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='horas_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_os',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número da OS'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pecas_aplicadas',
            field=models.TextField(blank=True, null=True, verbose_name='Registo de Peças Aplicadas'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servicos_executados',
            field=models.TextField(blank=True, null=True, verbose_name='Registo de Serviços Executados'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('REPARACAO', 'Reparação'), ('MANUTENCAO', 'Manutenção'), ('GARANTIA', 'Garantia')], default='REPARACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('DIAGNOSTICO', 'Em diagnóstico'), ('REPARACAO', 'Em reparação'), ('AGUARDANDO_PECAS', 'A aguardar peças'), ('FINALIZADO', 'Finalizado'), ('ENTREGUE', 'Entregue')], default='RECEBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_pecas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.veiculo', verbose_name='Viatura'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Matrícula'),
        ),
        migrations.DeleteModel(
            name='PlanoManutencao',
        ),
    ]
