# Generated by Django 6.0.2 on 2026-02-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_remove_ordemservico_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_fechamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='pecas_aplicadas',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos_executados',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_pecas',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_avaria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='diagnostico_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.veiculo'),
        ),
        migrations.CreateModel(
            name='PecaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='gestao.ordemservico')),
            ],
        ),
    ]
