# Generated by Django 6.0.2 on 2026-02-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_remove_ordemservico_data_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_avaria',
            field=models.TextField(verbose_name='Descrição da Avaria'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='diagnostico_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico Técnico'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='horas_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas de Mão de Obra'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10, verbose_name='Valor por Hora (€)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.veiculo', verbose_name='Viatura'),
        ),
        migrations.AlterField(
            model_name='pecaos',
            name='nome_peca',
            field=models.CharField(max_length=100, verbose_name='Nome da Peça'),
        ),
        migrations.AlterField(
            model_name='pecaos',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (€)'),
        ),
    ]
