# Generated by Django 6.0.2 on 2026-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_ordemservico_data_fechamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='pecaos',
            options={'verbose_name': 'Peça da OS', 'verbose_name_plural': 'Peças da OS'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Viatura', 'verbose_name_plural': 'Viaturas'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_avaria',
            field=models.TextField(verbose_name='Descrição da Avaria/Solicitação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('REPARACAO', 'Reparação Corretiva'), ('MANUTENCAO', 'Manutenção Preventiva'), ('GARANTIA', 'Garantia')], default='REPARACAO', max_length=20),
        ),
    ]
