# Generated by Django 6.0.2 on 2026-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_ordemservico_options_alter_pecaos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pecaos',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_avaria',
            field=models.TextField(verbose_name='Descrição da Avaria'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='horas_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Mão de Obra'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10, verbose_name='Valor/Hora (€)'),
        ),
    ]
