# Generated by Django 6.0.2 on 2026-02-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_pecaos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='km_atual',
            field=models.PositiveIntegerField(default=0, verbose_name='Quilometragem Atual'),
        ),
        migrations.CreateModel(
            name='DetalheIntervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_detalhado', models.TextField(blank=True, help_text='Histórico da avaria e diagnóstico identificado', null=True, verbose_name='Registo do Diagnóstico')),
                ('garantia_aplicavel', models.BooleanField(default=False, verbose_name='Associação a Garantia')),
                ('plano_km', models.PositiveIntegerField(blank=True, help_text='Ex: a cada 10.000 km', null=True, verbose_name='Plano por Quilometragem (km)')),
                ('plano_tempo_meses', models.PositiveIntegerField(blank=True, help_text='Ex: Revisão anual = 12', null=True, verbose_name='Plano por Tempo (meses)')),
                ('proxima_revisao_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próxima Revisão (KM)')),
                ('proxima_revisao_data', models.DateField(blank=True, null=True, verbose_name='Próxima Revisão (Data)')),
                ('alertas_ativos', models.BooleanField(default=True, verbose_name='Alertas Automáticos')),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe_planeamento', to='gestao.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Detalhe de Reparação/Manutenção',
                'verbose_name_plural': 'Ordens de Reparação e Manutenção',
            },
        ),
    ]
