# Generated by Django 6.0.2 on 2026-02-18 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_veiculo_km_atual_detalheintervencao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mecânico Atribuído'),
        ),
        migrations.AddField(
            model_name='pecaos',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca Utilizada'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='telemovel_proprietario',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telemóvel para SMS'),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='diagnostico_detalhado',
            field=models.TextField(blank=True, null=True, verbose_name='Registo do Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='plano_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plano por Quilometragem (km)'),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='plano_tempo_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plano por Tempo (meses)'),
        ),
        migrations.AlterField(
            model_name='pecaos',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Qtd'),
        ),
    ]
