# Generated by Django 6.0.2 on 2026-02-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_ordemservico_mecanico_pecaos_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='email_proprietario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para Notificações'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.CharField(default='Cliente', max_length=100, verbose_name='Nome do Proprietário'),
        ),
        migrations.AlterField(
            model_name='pecaos',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário (€)'),
        ),
    ]
