# Generated by Django 6.0.2 on 2026-02-18 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_veiculo_email_proprietario_veiculo_proprietario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Mecânico Atribuído'),
        ),
    ]
