# Generated by Django 6.0.2 on 2026-02-19 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_alter_ordemservico_mecanico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalheintervencao',
            options={},
        ),
        migrations.RemoveField(
            model_name='detalheintervencao',
            name='plano_km',
        ),
        migrations.RemoveField(
            model_name='detalheintervencao',
            name='plano_tempo_meses',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_atribuicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Trabalho'),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='alertas_ativos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='diagnostico_detalhado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='garantia_aplicavel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='ordem_servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe_planeamento', to='gestao.ordemservico'),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='proxima_revisao_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalheintervencao',
            name='proxima_revisao_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Trabalho'),
        ),
    ]
