# Generated by Django 6.0.2 on 2026-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_alter_detalheintervencao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaos',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='email_proprietario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
