# Generated by Django 6.0.2 on 2026-02-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_pecaos_confirmado_alter_veiculo_email_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Referência/SKU')),
                ('quantidade_em_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda_padrao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Peça em Stock',
                'verbose_name_plural': 'Peças em Stock',
            },
        ),
        migrations.AddField(
            model_name='pecaos',
            name='peca_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.pecastock', verbose_name='Vincular ao Stock'),
        ),
    ]
