# Generated by Django 6.0.2 on 2026-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0019_pecastock_pecaos_peca_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgente', 'Urgente')], default='Normal', max_length=10, verbose_name='Tipo de Serviço'),
        ),
    ]
