# Generated by Django 6.0.2 on 2026-03-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_ordemservico_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgente', 'Urgente')], default='Normal', max_length=10, verbose_name='Prioridade'),
        ),
    ]
